name: CI & Deploy to Raspberry Pi with Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_USERNAME: panliyong
  DOCKER_IMAGE: salarisonderhandeling
  PORT: 8502
  CONTAINER: salaris

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.12"

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Run pytest
        run: python -m pytest

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: panliyong
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --platform linux/arm64 \
            -t $DOCKER_USERNAME/$DOCKER_IMAGE:latest \
            --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    steps:
      - name: SSH in Pi and Pull & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: "${{ secrets.PI_PASSWORD }}"
          script: |
            docker pull --platform linux/arm64 panliyong/salarisonderhandeling:latest
            docker stop salaris || true
            docker rm salaris || true
            docker run -d --name salaris --publish 8502:8501 --restart always panliyong/salarisonderhandeling
