name: Deploy to Raspberry Pi with Docker
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
    
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u panliyong --password-stdin
    
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --platform linux/arm64 \
            -t panliyong/salarisonderhandeling:latest \
            --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == "push" && github.ref == "refs/heads/main"
    steps:
      - name: SSH in Pi and Pull & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: "${{ secrets.PI_PASSWORD }}"
          script: |
            docker pull --platform linux/arm64 panliyong/salarisonderhandeling
            docker stop salaris || true
            docker rm salaris || true
            docker run -d --name salaris -p 8502:8501 panliyong/salarisonderhandeling
