name: Deploy to Raspberry Pi with Docker
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  DOCKER_USERNAME: panliyong
  DOCKER_IMAGE: salarisonderhandeling
  PORT: 8502
  CONTAINER: salaris
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "$DOCKER_USERNAME" --password-stdin
    
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx inspect --bootstrap
          docker buildx build \
            --platform linux/arm64 \
            -t "$DOCKER_USERNAME/$DOCKER_IMAGE:latest" \
            --push .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH in Pi and Pull & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USERNAME }}
          password: "${{ secrets.PI_PASSWORD }}"
          script: |
            echo "Using '$CONTAINER'"
            docker pull --platform linux/arm64 "$DOCKER_USERNAME/$DOCKER_IMAGE:latest"
            docker stop "$CONTAINER" || true
            docker rm "$CONTAINER" || true
            docker run -d --name "$CONTAINER" --publish $PORT:8501 --restart always "$DOCKER_USERNAME/$DOCKER_IMAGE"
